# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_continent', models.CharField(max_length=100)),
                ('description_continent', models.CharField(blank=True, max_length=1000)),
                ('lien_wiki_continent', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pays', models.CharField(max_length=255)),
                ('description_pays', models.CharField(blank=True, max_length=1000)),
                ('lein_wiki_pays', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_photo', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='SiteTouristique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_site', models.CharField(max_length=255)),
                ('description_site', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_user', models.CharField(max_length=255)),
                ('prenom_user', models.CharField(blank=True, max_length=255)),
                ('email_user', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_videos', models.CharField(max_length=255)),
            ],
        ),
    ]
