# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetouristique',
            name='photo',
            field=models.ImageField(default='', upload_to='media/'),
            preserve_default=False,
        ),
    ]
