# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racine', '0002_sitetouristique_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitetouristique',
            name='photo',
            field=models.ImageField(upload_to='media'),
        ),
    ]
