# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 01:11
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racine', '0003_auto_20151218_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitetouristique',
            name='photo',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/'), upload_to=''),
        ),
    ]
