# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-16 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racine', '0004_auto_20151218_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_lieu', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo_1', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
