# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-16 16:36
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racine', '0005_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='photo_1',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/'), upload_to=''),
        ),
    ]
